# Netlify Configuration for SmartLedger Frontend

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Environment variables (set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
  REACT_APP_BACKEND_URL = "https://your-backend-url.railway.app"
  REACT_APP_SUPABASE_URL = "https://your-project.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  REACT_APP_SITE_URL = "https://your-domain.netlify.app"
  REACT_APP_SITE_NAME = "SmartLedger"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
